create or replace view MARKETING_DATABASE.PUBLIC.V_KLAVIYOCRM_V2 as
select e.SEND_DATE,E_NEWSUB,E_REACTIVATE,E_STP_ENROLL,EMAILSENT from 
(select to_date(DATETIME) as SEND_DATE,
COUNT(CASE WHEN TYPE = 'Recurly Start Subscription' THEN 1 END) AS E_NEWSUB,
COUNT(CASE WHEN TYPE = 'Subscription Reactivated' THEN 1 END) AS E_REACTIVATE,
COUNT(CASE WHEN TYPE = 'STP Enrollment' THEN 1 END) AS E_STP_ENROLL
FROM MARKETING_DATABASE.KLAVIYO.EVENT 
WHERE PROPERTY_ATTRIBUTION IS NOT NULL
AND SEND_DATE >= '2020-01-01'
GROUP BY SEND_DATE) as e
LEFT JOIN (select to_date(DATETIME) as SEND_DATE, COUNT(TYPE) as EMAILSENT
from MARKETING_DATABASE.KLAVIYO.EVENT 
WHERE TYPE = 'Received Email'
AND SEND_DATE >= '2020-01-01'
GROUP BY SEND_DATE
ORDER BY SEND_DATE ASC) as s on e.SEND_DATE = s.SEND_DATE
ORDER BY e.SEND_DATE ASC;