create or replace view "MARKETING_DATABASE"."OCEANX_PRODUCTION"."VW_RPT_INVENTORY_v1.0"
as

  select *
  from "MARKETING_DATABASE"."OCEANX_PRODUCTION"."EXPORT_VW_RPT_INVENTORY"
  order by INVENTORY_LOCATION_ID, SNAPSHOT_DATE