create or replace view "MARKETING_DATABASE"."OCEANX_PRODUCTION"."VW_RPT_INVENTORYPHYSICALINBOUNDS_v1.0"
as

  select *
  from "MARKETING_DATABASE"."OCEANX_PRODUCTION"."EXPORT_VW_RPT_INVENTORYPHYSICALINBOUNDS"
  order by INVENTORY_PHYSICAL_ID, TRANSACTIONDATETIME