create or replace view SEED_DATA.DEV.V_COHORT_SUB_CUST_GROUPS_LTV(
	COHORT_GROUP,
	CREATED_MONTH_YEAR,
	COHORT_QUANTITY,
	ACTIVE_MONTH_0,
	ACTIVE_MONTH_1,
	ACTIVE_MONTH_2,
	ACTIVE_MONTH_3,
	ACTIVE_MONTH_4,
	ACTIVE_MONTH_5,
	ACTIVE_MONTH_6,
	ACTIVE_MONTH_7,
	ACTIVE_MONTH_8,
	ACTIVE_MONTH_9,
	ACTIVE_MONTH_10,
	ACTIVE_MONTH_11,
	ACTIVE_MONTH_12,
	ACTIVE_MONTH_13,
	ACTIVE_MONTH_14,
	ACTIVE_MONTH_15,
	ACTIVE_MONTH_16,
	ACTIVE_MONTH_17,
	ACTIVE_MONTH_18,
	ACTIVE_MONTH_19,
	ACTIVE_MONTH_20,
	ACTIVE_MONTH_21,
	ACTIVE_MONTH_22,
	ACTIVE_MONTH_23,
	ACTIVE_MONTH_24,
	ACTIVE_MONTH_25,
	ACTIVE_MONTH_26,
	ACTIVE_MONTH_27,
	ACTIVE_MONTH_28,
	ACTIVE_MONTH_29,
	ACTIVE_MONTH_30,
	ACTIVE_MONTH_31,
	ACTIVE_MONTH_32,
	ACTIVE_MONTH_33,
	ACTIVE_MONTH_34,
	ACTIVE_MONTH_35,
	ACTIVE_MONTH_36,
	ACTIVE_MONTH_37,
	ACTIVE_MONTH_38,
	ACTIVE_MONTH_39,
	ACTIVE_MONTH_40,
	ACTIVE_MONTH_41,
	ACTIVE_MONTH_42,
	ACTIVE_MONTH_43,
	ACTIVE_MONTH_44,
	ACTIVE_MONTH_45,
	ACTIVE_MONTH_46,
	ACTIVE_MONTH_47,
	ACTIVE_MONTH_48,
	ACTIVE_MONTH_49,
	ACTIVE_MONTH_50,
	ACTIVE_MONTH_51,
	ACTIVE_MONTH_52,
	ACTIVE_MONTH_53,
	ACTIVE_MONTH_54,
	ACTIVE_MONTH_55,
	ACTIVE_MONTH_56,
	ACTIVE_MONTH_57,
	ACTIVE_MONTH_58,
	ACTIVE_MONTH_59,
	ACTIVE_MONTH_60,
	ACTIVE_MONTH_61,
    ACTIVE_MONTH_62,
    ACTIVE_MONTH_63
) as 
with cohorts as (
SELECT
  'Total Customers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_TOTAL_CUS_COHORT_LTV
UNION ALL
SELECT
'Total Subscribers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_TOTAL_SUB_COHORT_LTV
UNION ALL
SELECT
'DS-01 Customers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_DS01_CUS_COHORT_LTV
UNION ALL
SELECT
'DS-01 Subscribers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_DS01_SUB_COHORT_LTV
UNION ALL
SELECT
'PDS-08 Customers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_PDS08_CUS_COHORT_LTV
UNION ALL
SELECT
'PDS-08 Subscribers' as COHORT_GROUP
, CREATED_MONTH_YEAR
, COHORT_QUANTITY
, ACTIVE_MONTH_0
, ACTIVE_MONTH_1
, ACTIVE_MONTH_2
, ACTIVE_MONTH_3
, ACTIVE_MONTH_4
, ACTIVE_MONTH_5
, ACTIVE_MONTH_6
, ACTIVE_MONTH_7
, ACTIVE_MONTH_8
, ACTIVE_MONTH_9
, ACTIVE_MONTH_10
, ACTIVE_MONTH_11
, ACTIVE_MONTH_12
, ACTIVE_MONTH_13
, ACTIVE_MONTH_14
, ACTIVE_MONTH_15
, ACTIVE_MONTH_16
, ACTIVE_MONTH_17
, ACTIVE_MONTH_18
, ACTIVE_MONTH_19
, ACTIVE_MONTH_20
, ACTIVE_MONTH_21
, ACTIVE_MONTH_22
, ACTIVE_MONTH_23
, ACTIVE_MONTH_24
, ACTIVE_MONTH_25
, ACTIVE_MONTH_26
, ACTIVE_MONTH_27
, ACTIVE_MONTH_28
, ACTIVE_MONTH_29
, ACTIVE_MONTH_30
, ACTIVE_MONTH_31
, ACTIVE_MONTH_32
, ACTIVE_MONTH_33
, ACTIVE_MONTH_34
, ACTIVE_MONTH_35
, ACTIVE_MONTH_36
, ACTIVE_MONTH_37
, ACTIVE_MONTH_38
, ACTIVE_MONTH_39
, ACTIVE_MONTH_40
, ACTIVE_MONTH_41
, ACTIVE_MONTH_42
, ACTIVE_MONTH_43
, ACTIVE_MONTH_44
, ACTIVE_MONTH_45
, ACTIVE_MONTH_46
, ACTIVE_MONTH_47
, ACTIVE_MONTH_48
, ACTIVE_MONTH_49
, ACTIVE_MONTH_50
, ACTIVE_MONTH_51
, ACTIVE_MONTH_52
, ACTIVE_MONTH_53
, ACTIVE_MONTH_54
, ACTIVE_MONTH_55
, ACTIVE_MONTH_56
, ACTIVE_MONTH_57
, ACTIVE_MONTH_58
, ACTIVE_MONTH_59
, ACTIVE_MONTH_60
, ACTIVE_MONTH_61
, ACTIVE_MONTH_62
, ACTIVE_MONTH_63
FROM SEED_DATA.DEV.COHORT_PDS08_SUB_COHORT_LTV
) 
select 
*
from cohorts
--where CREATED_MONTH_YEAR <= DATEADD(month, -1, date_trunc('month',to_date(current_date())))
order by 1,2;