create or replace view SEED_DATA.DEV.V_MARKETING_CHANNEL_SPEND_MANUAL(
	DATE,
	TYPE,
	CATEGORY,
	CHANNEL,
	PRODUCT,
	SOURCE,
	SPEND,
	CONVERSIONS
) as 

WITH manual_marketing_spend AS (

select 
TO_VARCHAR(DATE::date, 'YYYY-MM-DD') AS DATE,
'MANUAL' AS TYPE,
'IHEART' AS SOURCE,
CHANNEL AS CATEGORY,
NAME AS CHANNEL,
PRODUCT,
SPEND,
SALES AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_IHEART

UNION ALL

select 
DATE,
'MANUAL' AS TYPE,
'INFLUENCER' AS SOURCE,
CHANNEL AS CATEGORY,
NAME AS CHANNEL,
PRODUCT,
SPEND,
SAME_MONTH_REDEMPTIONS AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_INFLUENCER

UNION ALL

select 
TO_VARCHAR(DATE::date, 'YYYY-MM-DD') AS DATE,
'MANUAL' AS TYPE,
'MISC' AS SOURCE,
CHANNEL AS CATEGORY,
NAME AS CHANNEL,
PRODUCT,
COST AS SPEND,
SUBS AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_MISC

UNION ALL

select 
TO_VARCHAR(DATE::date, 'YYYY-MM-DD') AS DATE,
'MANUAL' AS TYPE,
'PCA' AS SOURCE,
CHANNEL AS CATEGORY,
NAME AS CHANNEL,
PRODUCT,
COST AS SPEND,
0 AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_PCA
/*
UNION ALL

select 
_DATE AS DATE,
'MANUAL' AS TYPE,
'PINTEREST' AS SOURCE,
CATEGORY,
CHANNEL,
_PRODUCT as PRODUCT,
_COST AS SPEND,
_WEB_CONVERSIONS_CHECKOUT_ AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_PINTEREST
*/
UNION ALL

select 
DATE,
'MANUAL' AS TYPE,
'QUORA' AS SOURCE,
CATEGORY,
CHANNEL,
PRODUCT,
COST AS SPEND,
CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_QUORA

UNION ALL

select 
DATE,
'MANUAL' AS TYPE,
'SPOTIFY' AS SOURCE,
CHANNEL AS CATEGORY,
NAME,
PRODUCT,
SPEND,
SALES AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_SPOTIFY

UNION ALL

select 
TO_VARCHAR(DATE::date, 'YYYY-MM-DD') AS DATE,
'MANUAL' AS TYPE,
'TAPJOY' AS SOURCE,
CATEGORY,
CHANNEL,
PRODUCT,
COST AS SPEND,
SUBS AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_TAPJOY

UNION ALL

select 
TO_VARCHAR(DATE::date, 'YYYY-MM-DD') AS DATE,
'MANUAL' AS TYPE,
'INFLUENCERAGENCY' AS SOURCE,
TYPE AS CATEGORY,
VENDOR AS CHANNEL,
PRODUCT,
SPEND,
0 AS CONVERSIONS
---SELECT *
from MARKETING_DATABASE.GOOGLE_SHEETS.MRKT_SPEND_INFLUENCERAGENCY

)

SELECT
d.date,
mms.type,
UPPER(mms.category) AS category,
UPPER(mms.channel) as channel,
UPPER(mms.product) as product,
mms.source,
ifnull(sum(mms.spend),0) as spend,
ifnull(sum(mms.conversions),0) as conversions
FROM SEED_DATA.DEV.DIM_DATE as d
left join manual_marketing_spend as mms
on d.date = mms.date
--where d.date between '2023-01-01' and to_date(current_date())
where source is not null
group by 1,2,3,4,5,6
order by 1 desc 
;