create or replace view SEED_DATA.DEV.V_MARKETING_CHANNEL_SPEND_PIVOT as 

WITH PIVOT_BUILD AS (
SELECT DATE, SOURCE, SPEND FROM SEED_DATA.DEV.V_MARKETING_CHANNEL_SPEND_ALL
where concat(SOURCE,'-',TYPE) <> 'PINTEREST-MANUAL'
)


SELECT *
  FROM PIVOT_BUILD
    PIVOT(SUM(spend) FOR SOURCE IN 
(
  'BING'
, 'FACEBOOK'
, 'GEIST'
, 'IHEART'
, 'INFLUENCER'
, 'INFLUENCERAGENCY'
, 'MISC'
, 'OUTBRAIN'
, 'PCA'
, 'PINTEREST'
, 'QUORA'
, 'REDDIT'
, 'SNAPCHAT'
, 'SPOTIFY'
, 'TAPJOY'
, 'TIKTOK'
, 'TRADEDESK'
, 'GOOGLE ADS'
))
      AS p
;