create or replace view SEED_DATA.DEV.V_ORDER_HISTORY(
	INVOICE_ID,
	INVOICE_NUMBER,
	TRANSACTION_ID,
	CUSTOMER_ID,
	CUSTOMER_EMAIL,
	SUBSCRIPTION_ID,
	INVOICE_DATE,
	SKU,
	SKU_DESCRIPTION,
	PROMOTION_CODE,
	PLATFORM_ORIG,
	QUANTITY,
	BASE_PRICE,
	TOTAL_AMOUNT_PAID,
	TAX,
	DISCOUNT,
	AMOUNT_PAID_BY_TRANSACTION,
	TOTAL_SHIPPING_COST,
	SHIPPING_COST_WO_TAX,
	SHIPPING_COST_TAX,
	AMOUNT_REFUNDED,
	CREDIT_APPLIED,
    PRODUCT,
    CLEAN_SKU
) as 


WITH complete as (
SELECT 
  CAST(INVOICE_ID as STRING) as INVOICE_ID
, NULL AS INVOICE_NUMBER
, CAST(TRANSACTION_ID as STRING) as TRANSACTION_ID
, CAST(CUSTOMER_ID as STRING) as CUSTOMER_ID
, CUSTOMER_EMAIL
, CAST(SUBSCRIPTION_ID as STRING) as SUBSCRIPTION_ID
, ORDER_DATE AS INVOICE_DATE
--, PAID_DATE
, SKU
, NULL AS SKU_DESCRIPTION
, DISCOUNT_CODE AS PROMOTION_CODE
, 'RECHARGE' as PLATFORM_ORIG
, IFNULL(SUM(QUANTITY),0) AS QUANTITY
, IFNULL(SUM(BASE_PRICE),0) AS BASE_PRICE
, IFNULL(SUM(TOTAL_AMOUNT_PAID),0) AS TOTAL_AMOUNT_PAID
, IFNULL(SUM(TAX),0) AS TAX
, IFNULL(SUM(DISCOUNT),0) AS DISCOUNT
--, NULL AS NORM_FACTOR
, 0 AS AMOUNT_PAID_BY_TRANSACTION
, IFNULL(SUM(SHIPPING_COST),0) AS TOTAL_SHIPPING_COST
, 0 AS SHIPPING_COST_WO_TAX
, 0 AS SHIPPING_COST_TAX
, IFNULL(SUM(REFUND_AMOUNT),0) AS AMOUNT_REFUNDED
, 0 AS CREDIT_APPLIED

FROM SEED_DATA.DEV.V_REHCARGE_ORDER_HISTORY 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11

UNION ALL

SELECT 
  INVOICE_ID
, INVOICE_NUMBER
, TRANSACTION_ID
, CUSTOMER_ID
, NULL AS CUSTOMER_EMAIL
, SUBSCRIPTION_ID
, INVOICE_DATE
--, PAID_DATE
, SKU
, SKU_DESCRIPTION
, PROMOTION_CODE
, 'RECURLY' as PLATFORM_ORIG
, IFNULL(SUM(QUANTITY),0) AS QUANTITY
, IFNULL(SUM(BASE_PRICE),0) AS BASE_PRICE
, IFNULL(SUM(TOTAL_AMOUNT_PAID),0) AS TOTAL_AMOUNT_PAID
, IFNULL(SUM(TAX),0) AS TAX
, IFNULL(SUM(DISCOUNT),0) AS DISCOUNT
--, NORM_FACTOR
, IFNULL(SUM(AMOUNT_PAID_BY_TRANSACTION),0) AS AMOUNT_PAID_BY_TRANSACTION
, IFNULL(SUM(TOTAL_SHIPPING_COST),0) AS TOTAL_SHIPPING_COST
, IFNULL(SUM(SHIPPING_COST_WO_TAX),0) AS SHIPPING_COST_WO_TAX
, IFNULL(SUM(SHIPPING_COST_TAX),0) AS SHIPPING_COST_TAX
, IFNULL(SUM(AMOUNT_REFUNDED),0) AS AMOUNT_REFUNDED
, IFNULL(SUM(CREDIT_APPLIED),0) AS CREDIT_APPLIED

FROM SEED_DATA.DEV.V_RECURLY_ORDER_HISTORY
--where transaction_id <> '68e14bba8ee3cd03ed5a7a446899a5a0'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
)

--SELECT * FROM complete;

SELECT 
  INVOICE_ID
, INVOICE_NUMBER
, TRANSACTION_ID
, CUSTOMER_ID
, CUSTOMER_EMAIL
, SUBSCRIPTION_ID
, INVOICE_DATE
, SKU
, SKU_DESCRIPTION
, PROMOTION_CODE
, PLATFORM_ORIG
, IFNULL(SUM(QUANTITY),0) AS QUANTITY
, IFNULL(SUM(BASE_PRICE),0) AS BASE_PRICE
, IFNULL(SUM(TOTAL_AMOUNT_PAID),0) AS TOTAL_AMOUNT_PAID
, IFNULL(SUM(TAX),0) AS TAX
, IFNULL(SUM(DISCOUNT),0) AS DISCOUNT
, IFNULL(SUM(AMOUNT_PAID_BY_TRANSACTION),0) AS AMOUNT_PAID_BY_TRANSACTION
, IFNULL(SUM(TOTAL_SHIPPING_COST),0) AS TOTAL_SHIPPING_COST
, IFNULL(SUM(SHIPPING_COST_WO_TAX),0) AS SHIPPING_COST_WO_TAX
, IFNULL(SUM(SHIPPING_COST_TAX),0) AS SHIPPING_COST_TAX
, IFNULL(SUM(AMOUNT_REFUNDED),0) AS AMOUNT_REFUNDED
, IFNULL(SUM(CREDIT_APPLIED),0) AS CREDIT_APPLIED
, case when sku ilike '%syn%' or sku ilike 'ds01%' then 'DS-01'
       when sku ilike '%pds%' then 'PDS-08'
       else null 
       end as product
, case when product = 'DS-01' and sku ilike '%wk%' then 'DS-01 Welcome Kit'
       when product = 'DS-01' and sku ilike '%rf' then 'DS-01 Refill'
       when product = 'DS-01' and sku ilike '%2mo%' then 'DS-01 Refill - 2 Months'
       when product = 'DS-01' and sku ilike '%3mo%' then 'DS-01 SRP Refill - 3 Months'
       when product = 'DS-01' and sku ilike '%6mo%' then 'DS-01 SRP Refill - 6 Months'
       when product = 'DS-01' and sku ilike '%trial%' then 'DS-01 Trial'
       when product = 'PDS-08' and sku ilike '%wk%' then 'PDS-08 Welcome Kit'
       when product = 'PDS-08' and sku ilike '%rf' then 'PDS-08 Refill'
       when product = 'PDS-08' and sku ilike '%2mo%' then 'PDS-08 Refill - 2 Months'
       when product = 'PDS-08' and sku ilike '%3mo%' then 'PDS-08 SRP Refill - 3 Months'
       when product = 'PDS-08' and sku ilike '%6mo%' then 'PDS-08 SRP Refill - 6 Months'
       when product = 'PDS-08' and sku ilike '%trial%' then 'PDS-08 Trial'
       else null 
       end as clean_sku

FROM complete 
group by 1,2,3,4,5,6,7,8,9,10,11;