create or replace view SEED_DATA.DEV.V_REVENUE_HISTORY_AGG(
	INVOICE_DATE,
	INVOICE_MONTH,
	PRODUCT,
	SKU,
	INVOICE_TYPE,
	TOTAL_ACCOUNTS,
	TOTAL_SUBSCRIBERS,
	TOTAL_SUBSCRIPTIONS,
	TOTAL_ORDERS,
	SRP_SUBSCRIBERS,
	TOTAL_BASE_PRICE,
	TOTAL_AMOUNT_PAID,
	TOTAL_TAX,
	TOTAL_DISCOUNT,
	TOTAL_AMOUNT_PAID_BY_TRANSACTION,
	TOTAL_SHIPPING_COST,
	TOTAL_SHIPPING_COST_WO_TAX,
	TOTAL_SHIPPING_COST_TAX,
	TOTAL_AMOUNT_REFUNDED,
	TOTAL_CREDIT_APPLIED,
	TOTAL_GROSS_REVENUE,
	TOTAL_ADJ_GROSS_REVENUE,
	TOTAL_ADJ_TOTAL_PAID,
	TOTAL_ADJ_SUBTOTAL_PAID
) as

select 
INVOICE_DATE,
DATE_TRUNC('MONTH',INVOICE_DATE) as INVOICE_MONTH,
SKU_MASTER_ID as PRODUCT,
SKU,
Case when NEW_FLAG = 'Y' and REACTIVATION_FLAG = 'N' and RENEWAL_FLAG = 'N'  then 'NEW'
     when NEW_FLAG = 'N' and REACTIVATION_FLAG = 'Y' and RENEWAL_FLAG = 'N'  then 'REACTIVATION'
     when NEW_FLAG = 'N' and REACTIVATION_FLAG = 'N' and RENEWAL_FLAG = 'Y'  then 'RENEWAL'
     else 'OTHER'
     end as INVOICE_TYPE,
IFNULL(count(distinct CUSTOMER_ID),0) as TOTAL_ACCOUNTS,
IFNULL(COUNT(distinct SUBSCRIPTION_ID),0) as TOTAL_SUBSCRIBERS,
IFNULL(SUM(QUANTITY),0) as TOTAL_SUBSCRIPTIONS,
IFNULL(COUNT(invoice_number),0) as TOTAL_ORDERS,
ifnull(SUM(case when SRP_FLAG = 'Y' then quantity end),0) SRP_SUBSCRIBERS,
ifnull(SUM(BASE_PRICE),0) as TOTAL_BASE_PRICE,
ifnull(SUM(TOTAL_AMOUNT_PAID),0) as TOTAL_AMOUNT_PAID,
ifnull(SUM(TAX),0) as TOTAL_TAX,
ifnull(SUM(DISCOUNT),0) as TOTAL_DISCOUNT,
ifnull(SUM(AMOUNT_PAID_BY_TRANSACTION),0) as TOTAL_AMOUNT_PAID_BY_TRANSACTION,
ifnull(SUM(TOTAL_SHIPPING_COST),0) as TOTAL_SHIPPING_COST,
ifnull(SUM(SHIPPING_COST_WO_TAX),0) as TOTAL_SHIPPING_COST_WO_TAX,
ifnull(SUM(SHIPPING_COST_TAX),0) as TOTAL_SHIPPING_COST_TAX,
ifnull(SUM(AMOUNT_REFUNDED),0) as TOTAL_AMOUNT_REFUNDED,
ifnull(SUM(CREDIT_APPLIED),0) as TOTAL_CREDIT_APPLIED,
ifnull(SUM(gross_revenue),0) as TOTAL_GROSS_REVENUE,
ifnull(SUM(adj_gross_revenue),0) as TOTAL_ADJ_GROSS_REVENUE,
ifnull(SUM(adj_total_paid),0) as TOTAL_ADJ_TOTAL_PAID,
ifnull(SUM(adj_subtotal_paid),0) as TOTAL_ADJ_SUBTOTAL_PAID

from "SEED_DATA"."DEV"."V_REVENUE_HISTORY" 
--where INVOICE_DATE = '2023-07-01' 
group by 1,2,3,4,5 order by 1 asc;